services:
  app:
    image: openjdk:17-oracle
    container_name: order_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - order_network
    restart: on-failure
    links:
        - mariadb:order_app

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_DATABASE: order
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - order_network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  order_network:
    driver: bridge
volumes:
    mariadb_data: